/*ALTERAÇÕES*/
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE funcionario
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE funcionario
MODIFY COLUMN telefone_alternativo VARCHAR(16) UNIQUE;

 ALTER TABLE contafuncionario
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE grupo
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `grupo`
MODIFY COLUMN data_fim TIMESTAMP;

ALTER TABLE viagem
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `viagem`
MODIFY COLUMN hora_fim TIMESTAMP;

ALTER TABLE carrinha
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE carrinhamotorista
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE avaria
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE carrinhaavaria
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE rota
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE zona
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE zonarota
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE rotagrupo
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE encarregado
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE contaencarregado
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE avaria
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE rotacrianca
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE entrega
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE carrinha
ADD COLUMN data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE avaria 
DROP COLUMN descricaco;

SET FOREIGN_KEY_CHECKS = 1;