/*ALTERAÇÕES*/
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE funcionario
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE funcionario
MODIFY COLUMN telefone_alternativo VARCHAR(16) UNIQUE;

 ALTER TABLE contafuncionario
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE grupo
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `grupo`
MODIFY COLUMN data_fim TIMESTAMP;

ALTER TABLE viagem
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `viagem`
MODIFY COLUMN hora_fim TIMESTAMP;

ALTER TABLE carrinha
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE carrinhamotorista
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE avaria
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE carrinhaavaria
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE rota
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE zona
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE zonarota
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE rotagrupo
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE encarregado
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE contaencarregado
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE avaria
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE rotacrianca
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE entrega
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE carrinha
ADD COLUMN data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE avaria 
DROP COLUMN descricaco;

ALTER TABLE funcionario
ADD COLUMN data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN data_actualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE contafuncionario
ADD COLUMN data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN data_actualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE avaria
ADD COLUMN data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN data_actualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE grupo
ADD COLUMN data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN data_actualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE rota
ADD COLUMN data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN data_actualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE zona
ADD COLUMN data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN data_actualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE encarregado
ADD COLUMN data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN data_actualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE contaencarregado
ADD COLUMN data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN data_actualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE crianca
DROP FOREIGN KEY crianca_ibfk_1;

ALTER TABLE crianca
DROP COLUMN encarregado_id;

CREATE TABLE IF NOT EXISTS crianca_encarregado(
	crianca_id BIGINT NOT NULL,
    encarregado_id BIGINT NOT NULL,
    PRIMARY KEY(crianca_id, encarregado_id),
    FOREIGN KEY (crianca_id) REFERENCES crianca(id),
    FOREIGN KEY (encarregado_id) REFERENCES encarregado(id)
);

ALTER TABLE carrinha
MODIFY COLUMN matricula VARCHAR(50) NOT NULL UNIQUE;

CREATE TABLE IF NOT EXISTS perfil(
	id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY(id)
);

INSERT INTO perfil(nome)
VALUES
	('Educadora'),
    ('Gestor de transportes'),
	('Motorista'),
    ('Secretária');


ALTER TABLE contafuncionario
ADD COLUMN perfil_id BIGINT NOT NULL, 
ADD FOREIGN KEY (perfil_id) REFERENCES perfil(id);

ALTER TABLE contafuncionario
DROP COLUMN nome_utilizador;

SET FOREIGN_KEY_CHECKS = 1;